[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[dev]
  framework = "vite"
  command = "npm run dev"
  targetPort = 5173
  publish = "dist"
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
